# Generated by Django 4.0.5 on 2022-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order_placed',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='sent',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
