# Generated by Django 4.0.5 on 2022-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_orderstatus_canceled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_status',
            new_name='status_name',
        ),
    ]
